Title of the Assignment: Descriptive Statistics - Measures of Central Tendency and
variability
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a
dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variables. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the age
groups. Create a list that contains a numeric value for each response to the categorical
variable.
2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of
iris.csv dataset.
Provide the codes with outputs and explain everything that you do in this step.

In [5]:
import pandas as pd
import seaborn as sns

In [6]:
df=pd.read_csv('/content/Practical 3.1 adult.csv')
display(df.head())

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                32561 non-null  int64
 1   Workclass          32561 non-null  object
 2   Final Weight       32561 non-null  int64
 3   Education          32561 non-null  object
 4   EducationNum       32561 non-null  int64
 5   Marital Status     32561 non-null  object
 6   Occupation         32561 non-null  object
 7   Relationship       32561 non-null  object
 8   Race               32561 non-null  object
 9   Gender             32561 non-null  object
 10  Capital Gain       32561 non-null  int64
 11  capital loss       32561 non-null  int64
 12  Hours per Week     32561 non-null  int64
 13  Native Country     32561 non-null  object
 14  Income             32561 non-null  object
 15  Education_Numeric  32561 non-null  int64
dtypes: int64(7), object(9)
memory usage: 4.0+ MB

In [10]:
display(df.groupby('Workclass')['Age'].describe())

                    count       mean        std   min    25%   50%   75%   max
Workclass
?                  1836.0  40.960240  20.334587  17.0  21.00  35.0  61.0  90.0
Federal-gov         960.0  42.590625  11.509171  17.0  34.00  43.0  51.0  90.0
Local-gov          2093.0  41.751075  12.272856  17.0  32.00  41.0  50.0  90.0
Never-worked          7.0  20.571429   4.613644  17.0  18.00  18.0  21.5  30.0
Private           22696.0  36.797585  12.827721  17.0  26.00  35.0  45.0  90.0
Self-emp-inc       1116.0  46.017025  12.553194  17.0  37.00  45.0  54.0  84.0
Self-emp-not-inc   2541.0  44.969697  13.338162  17.0  35.00  44.0  54.0  90.0
State-gov          1298.0  39.436055  12.431065  17.0  30.00  39.0  48.0  81.0
Without-pay          14.0  47.785714  21.075610  19.0  23.75  57.0  65.0  72.0

In [9]:
df.shape

(32561, 16)

### Part 1: Descriptive Statistics for Adult Dataset
We will group the quantitative variable **Age** by the categorical variable **Education** to provide summary statistics and create a numeric response list.

In [7]:
import pandas as pd

# Using the existing dataframe 'df' loaded from adult.csv
# Clean column names in case of leading/trailing spaces
df.columns = df.columns.str.strip()

# 1. Provide summary statistics grouped by 'Education'
summary_stats = df.groupby('Education')['Age'].agg(['mean', 'median', 'min', 'max', 'std'])
print("Summary Statistics of Age grouped by Education:")
display(summary_stats)

# 2. Create a list that contains a numeric value for each response to the categorical variable
# We use factorize to create a unique mapping for each category
df['Education_Numeric'], category_list = pd.factorize(df['Education'])

print("\nNumeric mapping for Education categories (First 10 rows):")
display(df[['Education', 'Education_Numeric']].head(10))

print("\nUnique mapping list:")
mapping_df = pd.DataFrame({'Category': category_list, 'Numeric_Value': range(len(category_list))})
display(mapping_df)

Summary Statistics of Age grouped by Education:

                   mean  median  min  max        std
Education
10th          37.429796    34.0   17   90  16.720713
11th          32.355745    28.0   17   90  15.545485
12th          32.000000    28.0   17   79  14.334625
1st-4th       46.142857    46.0   19   90  15.615625
5th-6th       42.885886    42.0   17   84  15.557285
7th-8th       48.445820    50.0   17   90  16.092350
9th           41.060311    39.0   17   90  15.946862
Assoc-acdm    37.381443    36.0   19   90  11.095177
Assoc-voc     38.553546    37.0   19   84  11.631300
Bachelors     38.904949    37.0   19   90  11.912210
Doctorate     47.702179    47.0   24   80  11.784716
HS-grad       38.974479    37.0   17   90  13.541524
Masters       44.049913    43.0   18   90  11.068935
Preschool     42.764706    41.0   19   75  15.126914
Prof-school   44.746528    43.0   25   90  11.962477
Some-college  35.756275    34.0   17   90  13.474051

Numeric mapping for Education categories (First 10 rows):

    Education  Education_Numeric
0   Bachelors                  0
1   Bachelors                  0
2     HS-grad                  1
3        11th                  2
4   Bachelors                  0
5     Masters                  3
6         9th                  4
7     HS-grad                  1
8     Masters                  3
9   Bachelors                  0

Unique mapping list:

         Category  Numeric_Value
0       Bachelors              0
1         HS-grad              1
2            11th              2
3         Masters              3
4             9th              4
5    Some-college              5
6      Assoc-acdm              6
7       Assoc-voc              7
8         7th-8th              8
9       Doctorate              9
10    Prof-school             10
11        5th-6th             11
12           10th             12
13        1st-4th             13
14      Preschool             14
15           12th             15

### Alternative: Using LabelEncoder for Part 1
`LabelEncoder` is a standard tool in the Scikit-Learn library used for preprocessing data for machine learning.

In [11]:
from sklearn.preprocessing import LabelEncoder

# 1. Initialize the LabelEncoder
le = LabelEncoder()

# 2. Fit and transform the categorical column
# This creates a list of numeric values for each response
df['Education_LabelEncoded'] = le.fit_transform(df['Education'])

# 3. Provide summary statistics grouped by the original categorical variable
# (The logic for statistics remains the same regardless of how we encode)
le_summary = df.groupby('Education')['Age'].agg(['mean', 'median', 'min', 'max', 'std'])

print("Summary Statistics (Same result as before):")
display(le_summary)

# 4. Create the mapping list (The 'Translation Key')
# le.classes_ contains the unique categories in the order they were encoded
le_mapping = pd.DataFrame({
    'Category': le.classes_,
    'Numeric_Value': range(len(le.classes_))
})

print("\nNumeric mapping created by LabelEncoder (Note it is alphabetical):")
display(le_mapping)

Summary Statistics (Same result as before):

                   mean  median  min  max        std
Education
10th          37.429796    34.0   17   90  16.720713
11th          32.355745    28.0   17   90  15.545485
12th          32.000000    28.0   17   79  14.334625
1st-4th       46.142857    46.0   19   90  15.615625
5th-6th       42.885886    42.0   17   84  15.557285
7th-8th       48.445820    50.0   17   90  16.092350
9th           41.060311    39.0   17   90  15.946862
Assoc-acdm    37.381443    36.0   19   90  11.095177
Assoc-voc     38.553546    37.0   19   84  11.631300
Bachelors     38.904949    37.0   19   90  11.912210
Doctorate     47.702179    47.0   24   80  11.784716
HS-grad       38.974479    37.0   17   90  13.541524
Masters       44.049913    43.0   18   90  11.068935
Preschool     42.764706    41.0   19   75  15.126914
Prof-school   44.746528    43.0   25   90  11.962477
Some-college  35.756275    34.0   17   90  13.474051

Numeric mapping created by LabelEncoder (Note it is alphabetical):

         Category  Numeric_Value
0            10th              0
1            11th              1
2            12th              2
3         1st-4th              3
4         5th-6th              4
5         7th-8th              5
6             9th              6
7      Assoc-acdm              7
8       Assoc-voc              8
9       Bachelors              9
10      Doctorate             10
11        HS-grad             11
12        Masters             12
13      Preschool             13
14    Prof-school             14
15   Some-college             15

### Part 2: Statistical Details for Iris Dataset Species
In this step, we will load the Iris dataset and use the `describe()` method to display statistical details like mean, standard deviation, and percentiles for the species: 'Iris-setosa', 'Iris-versicolor', and 'Iris-virginica'.

In [12]:
import seaborn as sns
import pandas as pd

# Load the built-in iris dataset from seaborn
iris = sns.load_dataset('iris')

# Filter the dataset for the three species
# Note: Seaborn's iris dataset uses 'setosa', 'versicolor', 'virginica'
species_list = ['setosa', 'versicolor', 'virginica']

for species in species_list:
    print(f"\n--- Statistical Details for {species.capitalize()} ---")
    stats = iris[iris['species'] == species].describe(percentiles=[.25, .5, .75])
    display(stats)

--- Statistical Details for Setosa ---

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000

--- Statistical Details for Versicolor ---

       sepal_length  sepal_width  petal_length  petal_width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000

--- Statistical Details for Virginica ---

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000