In [31]:
import nltk
#nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
#nltk.download('averaged_perceptron_tagger')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [32]:
text= "Tokenization is the first step in text analytics. The process of breaking down a text paragraph into smaller chunks such as words or sentences is called Tokenization."

In [33]:
#Perform Tokenization , Sentence Tokenization
from nltk.tokenize import sent_tokenize
tokenized_text= sent_tokenize(text)
print(tokenized_text)
#Word Tokenization
from nltk.tokenize import word_tokenize
tokenized_word=word_tokenize(text)
print(tokenized_word)

['Tokenization is the first step in text analytics.', 'The process of breaking down a text paragraph into smaller chunks such as words or sentences is called Tokenization.']
['Tokenization', 'is', 'the', 'first', 'step', 'in', 'text', 'analytics', '.', 'The', 'process', 'of', 'breaking', 'down', 'a', 'text', 'paragraph', 'into', 'smaller', 'chunks', 'such', 'as', 'words', 'or', 'sentences', 'is', 'called', 'Tokenization', '.']

In [34]:
#Removing Punctuations and Stop Word
# print stop words of English

from nltk.corpus import stopwords
import re
stop_words=set(stopwords.words("english"))
print(stop_words)
text= "How to remove stop words with NLTK library in Python?"
text= re.sub('[^a-zA-Z]', ' ',text)
tokens = word_tokenize(text.lower())
filtered_text=[]
for w in tokens:
  if w not in stop_words:
    filtered_text.append(w)
print("Tokenized Sentence:",tokens)
print("Filterd Sentence:",filtered_text)

{"hasn't", 'same', "we're", 'down', 'from', 'over', 'didn', 'than', "aren't", "they'd", "we've", 'will', "they're", "it'll", "mustn't", 've', 'so', 'too', 'having', 'y', 'mightn', 'its', 'again', "i've", 'up', 'for', 'her', 'during', 'll', 'not', 's', 'after', "won't", 'ain', "doesn't", "it'd", 'very', 'weren', "mightn't", 'were', 'out', "we'd", 'been', "it's", 'yourselves', "you'd", "i'd", 'there', 'before', 'the', 'until', 'isn', 'that', 'against', 'by', "hadn't", "wouldn't", 'she', 'but', 'into', 'mustn', 'now', 'on', "you've", 'below', 'and', 'about', 'd', "i'm", "you'll", 'be', 'is', 'shan', 'why', 'those', 'at', 'have', 'this', 'between', 'my', 'yours', 'theirs', 'who', 'few', 'shouldn', 'o', "isn't", 'their', 'hers', 'when', 'his', "she's", 'wouldn', 'in', 'couldn', 'ma', 'own', 'whom', 'both', "haven't", 'me', 'won', 'as', 'no', "we'll", 'nor', 'off', 'does', 'are', 'these', 'you', 'needn', 'ourselves', 'how', "needn't", 'just', 'under', 'had', 'all', 'himself', 'themselves', 'doesn', 'further', 'above', 'what', 'doing', 'of', 'hadn', "she'd", 'can', 'myself', 'ours', "i'll", 'most', 'through', 'such', "couldn't", "they'll", 'or', 'some', 'more', "he'd", "she'll", 'has', 'm', 'herself', "that'll", 'am', 'only', 'we', 'any', "didn't", 'here', 'with', "don't", "he'll", 'a', 'then', 'don', 'if', 'itself', 'where', 'being', 'to', 'your', 'them', 'wasn', 're', "should've", 'i', 'each', 'it', "weren't", 'should', 'other', "they've", 'because', 'him', 'do', 'yourself', 'which', 'while', 'an', 'did', 't', "shan't", "he's", 'aren', 'our', "you're", 'he', 'once', 'haven', 'was', 'hasn', "shouldn't", "wasn't", 'they'}
Tokenized Sentence: ['how', 'to', 'remove', 'stop', 'words', 'with', 'nltk', 'library', 'in', 'python']
Filterd Sentence: ['remove', 'stop', 'words', 'nltk', 'library', 'python']

In [35]:
#Perform Stemming
from nltk.stem import PorterStemmer
e_words= ["wait", "waiting", "waited", "waits"]
ps =PorterStemmer()
for w in e_words:
  rootWord=ps.stem(w)
  print(rootWord)

wait
wait
wait
wait

In [36]:
#Perform Lemmatization
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
text = "studies studying cries cry"
tokenization = nltk.word_tokenize(text)
for w in tokenization:
  print("Lemma for {} is {}".format(w, wordnet_lemmatizer.lemmatize(w)))

Lemma for studies is study
Lemma for studying is studying
Lemma for cries is cry
Lemma for cry is cry

In [37]:
#Apply POS Tagging to text
import nltk
from nltk.tokenize import word_tokenize
data="The pink sweater fit her perfectly"
words=word_tokenize(data)
for word in words:
    print(nltk.pos_tag([word]))

[('The', 'DT')]
[('pink', 'NN')]
[('sweater', 'NN')]
[('fit', 'NN')]
[('her', 'PRP$')]
[('perfectly', 'RB')]

In [38]:
# Algorithm for Create representation of document by calculating TFIDF

In [39]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
documentA = 'Jupiter is the largest Planet'
documentB = 'Mars is the fourth planet from the Sun'

In [41]:
#Create BagofWords (BoW) for Document A and B.
bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')

In [42]:
bagOfWordsA

['Jupiter', 'is', 'the', 'largest', 'Planet']

In [43]:
bagOfWordsB

['Mars', 'is', 'the', 'fourth', 'planet', 'from', 'the', 'Sun']

In [44]:
# Create Collection of Unique words from Document A and B.
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

In [45]:
uniqueWords

{'Jupiter',
 'Mars',
 'Planet',
 'Sun',
 'fourth',
 'from',
 'is',
 'largest',
 'planet',
 'the'}

In [46]:
# Create a dictionary of words and their occurrence for each document in the corpus
numOfWordsA = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsA:
  numOfWordsA[word] += 1
numOfWordsB = dict.fromkeys(uniqueWords, 0)
for word in bagOfWordsB:
  numOfWordsB[word] += 1

In [47]:
numOfWordsA

{'Mars': 0,
 'the': 1,
 'fourth': 0,
 'Planet': 1,
 'from': 0,
 'Jupiter': 1,
 'largest': 1,
 'is': 1,
 'Sun': 0,
 'planet': 0}

In [48]:
numOfWordsB

{'Mars': 1,
 'the': 2,
 'fourth': 1,
 'Planet': 0,
 'from': 1,
 'Jupiter': 0,
 'largest': 0,
 'is': 1,
 'Sun': 1,
 'planet': 1}

In [49]:
# Compute the term frequency for each of our documents.

In [50]:
def computeTF(wordDict, bagOfWords):
  tfDict = {}
  bagOfWordsCount = len(bagOfWords)
  for word, count in wordDict.items():
    tfDict[word] = count / float(bagOfWordsCount)
  return tfDict
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)

In [51]:
tfA

{'Mars': 0.0,
 'the': 0.2,
 'fourth': 0.0,
 'Planet': 0.2,
 'from': 0.0,
 'Jupiter': 0.2,
 'largest': 0.2,
 'is': 0.2,
 'Sun': 0.0,
 'planet': 0.0}

In [52]:
tfB

{'Mars': 0.125,
 'the': 0.25,
 'fourth': 0.125,
 'Planet': 0.0,
 'from': 0.125,
 'Jupiter': 0.0,
 'largest': 0.0,
 'is': 0.125,
 'Sun': 0.125,
 'planet': 0.125}

In [53]:
# Compute the term Inverse Document Frequency.
def computeIDF(documents):
  import math
  N = len(documents)
  idfDict = dict.fromkeys(documents[0].keys(), 0)
  for document in documents:
    for word, val in document.items():
      if val > 0:
        idfDict[word] += 1
  for word, val in idfDict.items():
    idfDict[word] = math.log(N / float(val))
  return idfDict
idfs = computeIDF([numOfWordsA, numOfWordsB])
idfs

{'Mars': 0.6931471805599453,
 'the': 0.0,
 'fourth': 0.6931471805599453,
 'Planet': 0.6931471805599453,
 'from': 0.6931471805599453,
 'Jupiter': 0.6931471805599453,
 'largest': 0.6931471805599453,
 'is': 0.0,
 'Sun': 0.6931471805599453,
 'planet': 0.6931471805599453}

In [54]:
# Compute the term TF/IDF for all words.
def computeTFIDF(tfBagOfWords, idfs):
  tfidf = {}
  for word, val in tfBagOfWords.items():
    tfidf[word] = val * idfs[word]
  return tfidf

tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df = pd.DataFrame([tfidfA, tfidfB])

In [55]:
df

,Mars,the,fourth,Planet,from,Jupiter,largest,is,Sun,planet
0,0.000000,0.0,0.000000,0.138629,0.000000,0.138629,0.138629,0.0,0.000000,0.000000
1,0.086643,0.0,0.086643,0.000000,0.086643,0.000000,0.000000,0.0,0.086643,0.086643

In [56]:
tfidfA

{'Mars': 0.0,
 'the': 0.0,
 'fourth': 0.0,
 'Planet': 0.13862943611198905,
 'from': 0.0,
 'Jupiter': 0.13862943611198905,
 'largest': 0.13862943611198905,
 'is': 0.0,
 'Sun': 0.0,
 'planet': 0.0}

In [57]:
tfidfB

{'Mars': 0.08664339756999316,
 'the': 0.0,
 'fourth': 0.08664339756999316,
 'Planet': 0.0,
 'from': 0.08664339756999316,
 'Jupiter': 0.0,
 'largest': 0.0,
 'is': 0.0,
 'Sun': 0.08664339756999316,
 'planet': 0.08664339756999316}

In [58]:
df

,Mars,the,fourth,Planet,from,Jupiter,largest,is,Sun,planet
0,0.000000,0.0,0.000000,0.138629,0.000000,0.138629,0.138629,0.0,0.000000,0.000000
1,0.086643,0.0,0.086643,0.000000,0.086643,0.000000,0.000000,0.0,0.086643,0.086643