Data Wrangling, I
Perform the following operations using Python on any open source dataset (e.g., data.csv)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g. https://www.kaggle.com). Provide a clear
description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas data frame.
4. Data Preprocessing: check for missing values in the data using pandas insult(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking the
data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set.
If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
In addition to the codes and outputs, explain every operation that you do in the above steps and
explain everything that you do to import/read/scrape the data set.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the dataset
file_path = '/content/Practical 1 research_student (1).xlsx'#change this if required.
df = pd.read_excel(file_path)

# Display the first 5 rows
display(df.head())

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,...,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CIVIL,77.57,64.6,Male,BSEB Patna,BSEB Patna,OBC,6.29,44718.0,15.970714,...,5.94,5.41,6.25,6.13,1.0,4.0,3.0,2.0,0.0,5.0
2,CSE,86.40,71.8,Male,CBSE,CBSE,GEN,6.47,24222.0,8.650714,...,5.88,5.53,6.44,6.19,2.0,2.0,0.0,1.0,0.0,4.0
3,CSE,88.14,78.0,Male,ICSE,ICSE,GEN,7.35,24723.0,8.829643,...,6.54,6.41,6.50,6.69,1.0,1.0,3.0,0.0,0.0,5.0
4,CSE,65.40,59.8,Female,CBSE,CBSE,ST,6.41,232157.0,82.913214,...,5.71,5.24,5.88,6.25,2.0,0.0,2.0,2.0,0.0,1.0

### 4. Data Preprocessing

In this step, we will:
1. Check for missing values in each column.
2. Generate initial statistics for the numerical and categorical columns.
3. Identify the dimensions (rows and columns) of the dataset.
4. Provide a description of the variables.

In [3]:
# 1. Check for missing values
print("Missing Values per Column:")
display(df.isnull().sum())

# 2. Initial statistics
print("\nInitial Statistics (Numerical):")
display(df.describe())

# 3. Check dimensions
print(f"\nDimensions of the Data Frame: {df.shape}")

Missing Values per Column:

Branch                    3
Marks[10th]               3
Marks[12th]               3
Gender                    3
Board[10th]               3
Board[12th]               3
Category                  3
GPA 1                     3
Rank                      2
Normalized Rank           3
CGPA                      3
Current Back              3
Ever Back                 4
GPA 2                     3
GPA 3                     3
GPA 4                     3
GPA 5                     3
GPA 6                     3
Olympiads Qualified       3
Technical Projects        3
Tech Quiz                 3
Engg. Coaching            3
NTSE Scholarships         3
Miscellany Tech Events    3
dtype: int64

Initial Statistics (Numerical):

,Marks[10th],Marks[12th],GPA 1,Rank,Normalized Rank,CGPA,Current Back,Ever Back,GPA 2,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
count,220.000000,220.000000,220.000000,221.000000,220.000000,220.000000,220.000000,219.000000,220.000000,220.000000,220.000000,220.00000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000
mean,84.307455,77.783227,7.534409,42312.122172,14.725877,7.199468,0.077273,1.442922,7.266500,7.173500,7.287555,7.88933,7.554557,3.595455,1.854545,1.836364,2.972727,0.686364,1.504545
std,8.519507,9.044172,4.602384,38503.691510,12.528090,0.700186,0.267633,2.657892,4.426861,4.134494,4.509050,5.10414,0.961539,2.096960,1.373835,1.381729,2.053882,1.336798,2.215548
min,53.700000,56.800000,5.760000,11814.000000,4.219286,5.890000,0.000000,0.000000,5.760000,4.880000,4.900000,5.50000,4.560000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,79.000000,71.550000,6.710000,23949.000000,8.544196,6.637500,0.000000,0.000000,6.417500,6.317500,6.440000,6.81000,6.855000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000
50%,86.550000,79.100000,7.180000,30080.000000,10.694107,7.125000,0.000000,0.000000,6.880000,6.820000,6.955000,7.63000,7.500000,4.000000,2.000000,2.000000,3.000000,0.000000,0.000000
75%,91.000000,85.250000,7.760000,41527.000000,14.718036,7.702500,0.000000,2.000000,7.470000,7.410000,7.485000,8.25000,8.190000,5.000000,3.000000,3.000000,4.000000,1.000000,4.000000
max,96.600000,96.500000,74.700000,279839.000000,99.942500,9.010000,1.000000,13.000000,71.800000,67.200000,72.900000,81.90000,9.810000,10.000000,5.000000,7.000000,10.000000,7.000000,5.000000

Dimensions of the Data Frame: (223, 24)

In [4]:
# 4. Variable Types and Descriptions
print("Variable Info:")
display(df.info())

Variable Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Branch                  220 non-null    object
 1   Marks[10th]             220 non-null    float64
 2   Marks[12th]             220 non-null    float64
 3   Gender                  220 non-null    object
 4   Board[10th]             220 non-null    object
 5   Board[12th]             220 non-null    object
 6   Category                220 non-null    object
 7   GPA 1                   220 non-null    float64
 8   Rank                    221 non-null    float64
 9   Normalized Rank         220 non-null    float64
 10  CGPA                    220 non-null    float64
 11  Current Back            220 non-null    float64
 12  Ever Back               219 non-null    float64
 13  GPA 2                   220 non-null    float64
 14  GPA 3                   220 non-null    float64
 15  GPA 4                   220 non-null    float64
 16  GPA 5                   220 non-null    float64
 17  GPA 6                   220 non-null    float64
 18  Olympiads Qualified     220 non-null    float64
 19  Technical Projects      220 non-null    float64
 20  Tech Quiz               220 non-null    float64
 21  Engg. Coaching          220 non-null    float64
 22  NTSE Scholarships       220 non-null    float64
 23  Miscellany Tech Events  220 non-null    float64
dtypes: float64(19), object(5)
memory usage: 41.9+ KB

None

### 5. Data Formatting and Data Normalization

In this step, we will:
1. Clean the dataset by removing empty rows.
2. Verify and convert data types where necessary.
3. Summarize the variables by their finalized types.

In [5]:
# Remove rows where all or most values are missing (cleaning up the trailing empty rows)
df.dropna(how='all', inplace=True)

# Handling specific type conversions if any categorical columns are stored as numeric or vice versa
# Based on df.info(), the types look mostly correct, but let's ensure 'Ever Back' is an integer after cleaning
df['Ever Back'] = df['Ever Back'].fillna(0).astype(int)

print("Updated Data Types:")
display(df.dtypes)

print("\nSummary of variable types:")
num_vars = df.select_dtypes(include=['number']).columns.tolist()
cat_vars = df.select_dtypes(include=['object']).columns.tolist()
print(f"Numerical variables: {len(num_vars)}")
print(f"Categorical variables: {len(cat_vars)}")

Updated Data Types:

Branch                     object
Marks[10th]               float64
Marks[12th]               float64
Gender                     object
Board[10th]                object
Board[12th]                object
Category                   object
GPA 1                     float64
Rank                      float64
Normalized Rank           float64
CGPA                      float64
Current Back              float64
Ever Back                   int64
GPA 2                     float64
GPA 3                     float64
GPA 4                     float64
GPA 5                     float64
GPA 6                     float64
Olympiads Qualified       float64
Technical Projects        float64
Tech Quiz                 float64
Engg. Coaching            float64
NTSE Scholarships         float64
Miscellany Tech Events    float64
dtype: object

Summary of variable types:
Numerical variables: 19
Categorical variables: 5

In [11]:
display(df.isnull().sum())

Branch                    0
Marks[10th]               0
Marks[12th]               0
Gender                    0
Board[10th]               0
Board[12th]               0
Category                  0
GPA 1                     0
Rank                      0
Normalized Rank           0
CGPA                      0
Current Back              0
Ever Back                 0
GPA 2                     0
GPA 3                     0
GPA 4                     0
GPA 5                     0
GPA 6                     0
Olympiads Qualified       0
Technical Projects        0
Tech Quiz                 0
Engg. Coaching            0
NTSE Scholarships         0
Miscellany Tech Events    0
Marks[10th]_normalized    0
Marks[12th]_normalized    0
GPA 1_normalized          0
CGPA_normalized           0
dtype: int64

### Note on Type Conversion
If a column is not in the correct data type, we use `astype()` or specific pandas conversion functions.

Example:
```python
# 1. Convert to numeric, forcing errors to NaN (useful for messy data)
df['Column_Name'] = pd.to_numeric(df['Column_Name'], errors='coerce')

# 2. Convert to integer after handling NaNs
df['Column_Name'] = df['Column_Name'].fillna(0).astype(int)

# 3. Convert to categorical string
df['Column_Name'] = df['Column_Name'].astype(str)
```

### 5. (Continued) Data Normalization

Normalization rescales numerical values to a range between 0 and 1. This is useful when different columns have different scales (e.g., Marks vs GPAs).

In [6]:
# Identify numerical columns for normalization
cols_to_normalize = ['Marks[10th]', 'Marks[12th]', 'GPA 1', 'CGPA']

# Min-Max Normalization: (x - min) / (max - min)
for col in cols_to_normalize:
    df[col + '_normalized'] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())

print("First 5 rows with normalized columns:")
# Fixed the display index syntax
columns_to_show = cols_to_normalize + [col + '_normalized' for col in cols_to_normalize]
display(df[columns_to_show].head())

First 5 rows with normalized columns:

,Marks[10th],Marks[12th],GPA 1,CGPA,Marks[10th]_normalized,Marks[12th]_normalized,GPA 1_normalized,CGPA_normalized
1,77.57,64.6,6.29,6.02,0.556410,0.196474,0.007688,0.041667
2,86.40,71.8,6.47,6.10,0.762238,0.377834,0.010299,0.067308
3,88.14,78.0,7.35,6.65,0.802797,0.534005,0.023064,0.243590
4,65.40,59.8,6.41,6.09,0.272727,0.075567,0.009428,0.064103
5,81.00,74.0,6.80,6.13,0.636364,0.433249,0.015086,0.076923

### 6. Turn Categorical Variables into Quantitative Variables

We use One-Hot Encoding to create binary columns for each category.

In [7]:
# 1. On current dataset
# Let's encode 'Branch' and 'Gender'
df_encoded = pd.get_dummies(df, columns=['Branch', 'Gender'], prefix=['Br', 'Gen'])

print("Encoded DataFrame Shape:", df_encoded.shape)
display(df_encoded.filter(like='Br_').head())

# 2. What if it can't be done directly (e.g., if columns were already numerical codes)?
# You would first map them to strings or use LabelEncoder
# Example of manual mapping if 'Gender' was 1 and 2:
# df['Gender'] = df['Gender'].map({1: 'Male', 2: 'Female'})
# Then apply get_dummies as shown above.

Encoded DataFrame Shape: (221, 35)

   Br_CIVIL  Br_CSE  Br_ECE  Br_EEE  Br_IT  Br_MECH  Br_PROD
1      True   False   False   False  False    False    False
2     False    True   False   False  False    False    False
3     False    True   False   False  False    False    False
4     False    True   False   False  False    False    False
5     False    True   False   False  False    False    False

### Final Step: Summary of Preprocessed Data

Now that we have:
1. Handled missing values.
2. Formatted and converted data types.
3. Normalized numerical features.
4. Encoded categorical variables.

We will display the final descriptive statistics and the first few rows of the resulting DataFrame (`df_encoded`).

In [8]:
# Final statistics of the preprocessed dataset
print("Final Descriptive Statistics:")
display(df_encoded.describe())

# Final dimensions
print(f"\nFinal Dataset Dimensions: {df_encoded.shape}")

# Display the final head of the preprocessed data
print("\nFinal Preprocessed Data (First 5 rows):")
display(df_encoded.head())

Final Descriptive Statistics:

,Marks[10th],Marks[12th],GPA 1,Rank,Normalized Rank,CGPA,Current Back,Ever Back,GPA 2,GPA 3,...,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events,Marks[10th]_normalized,Marks[12th]_normalized,GPA 1_normalized,CGPA_normalized
count,220.000000,220.000000,220.000000,221.000000,220.000000,220.000000,220.000000,221.000000,220.000000,220.000000,...,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000
mean,84.307455,77.783227,7.534409,42312.122172,14.725877,7.199468,0.077273,1.429864,7.266500,7.173500,...,3.595455,1.854545,1.836364,2.972727,0.686364,1.504545,0.713460,0.528545,0.025738,0.419701
std,8.519507,9.044172,4.602384,38503.691510,12.528090,0.700186,0.267633,2.649325,4.426861,4.134494,...,2.096960,1.373835,1.381729,2.053882,1.336798,2.215548,0.198590,0.227813,0.066759,0.224419
min,53.700000,56.800000,5.760000,11814.000000,4.219286,5.890000,0.000000,0.000000,5.760000,4.880000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,79.000000,71.550000,6.710000,23949.000000,8.544196,6.637500,0.000000,0.000000,6.417500,6.317500,...,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.589744,0.371537,0.013780,0.239583
50%,86.550000,79.100000,7.180000,30080.000000,10.694107,7.125000,0.000000,0.000000,6.880000,6.820000,...,4.000000,2.000000,2.000000,3.000000,0.000000,0.000000,0.765734,0.561713,0.020598,0.395833
75%,91.000000,85.250000,7.760000,41527.000000,14.718036,7.702500,0.000000,2.000000,7.470000,7.410000,...,5.000000,3.000000,3.000000,4.000000,1.000000,4.000000,0.869464,0.716625,0.029011,0.580929
max,96.600000,96.500000,74.700000,279839.000000,99.942500,9.010000,1.000000,13.000000,71.800000,67.200000,...,10.000000,5.000000,7.000000,10.000000,7.000000,5.000000,1.000000,1.000000,1.000000,1.000000

Final Dataset Dimensions: (221, 35)

Final Preprocessed Data (First 5 rows):

,Marks[10th],Marks[12th],Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,CGPA,Current Back,...,CGPA_normalized,Br_CIVIL,Br_CSE,Br_ECE,Br_EEE,Br_IT,Br_MECH,Br_PROD,Gen_Female,Gen_Male
1,77.57,64.6,BSEB Patna,BSEB Patna,OBC,6.29,44718.0,15.970714,6.02,1.0,...,0.041667,True,False,False,False,False,False,False,False,True
2,86.40,71.8,CBSE,CBSE,GEN,6.47,24222.0,8.650714,6.10,1.0,...,0.067308,False,True,False,False,False,False,False,False,True
3,88.14,78.0,ICSE,ICSE,GEN,7.35,24723.0,8.829643,6.65,1.0,...,0.243590,False,True,False,False,False,False,False,False,True
4,65.40,59.8,CBSE,CBSE,ST,6.41,232157.0,82.913214,6.09,1.0,...,0.064103,False,True,False,False,False,False,False,True,False
5,81.00,74.0,CBSE,CBSE,GEN,6.80,23252.0,8.304286,6.13,1.0,...,0.076923,False,True,False,False,False,False,False,False,True

### Investigating the Rank Discrepancy
We will find the row where Rank exists but other major columns (like Branch or Marks) are missing to understand why the count is different.

In [9]:
# Identify the row(s) where Rank is present but Branch is missing
discrepancy_row = df[df['Rank'].notnull() & df['Branch'].isnull()]
print("Row(s) causing the count discrepancy:")
display(discrepancy_row)

Row(s) causing the count discrepancy:

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,...,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events,Marks[10th]_normalized,Marks[12th]_normalized,GPA 1_normalized,CGPA_normalized
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279839.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Drop the specific row causing the discrepancy (index 222)
df.drop(index=222, inplace=True)

# Also update df_encoded to match if it was generated from the old df
df_encoded = df_encoded[df_encoded.index != 222]

print("Row 222 dropped. Updated counts:")
display(df.info())

Row 222 dropped. Updated counts:
<class 'pandas.core.frame.DataFrame'>
Index: 220 entries, 1 to 220
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Branch                  220 non-null    object
 1   Marks[10th]             220 non-null    float64
 2   Marks[12th]             220 non-null    float64
 3   Gender                  220 non-null    object
 4   Board[10th]             220 non-null    object
 5   Board[12th]             220 non-null    object
 6   Category                220 non-null    object
 7   GPA 1                   220 non-null    float64
 8   Rank                    220 non-null    float64
 9   Normalized Rank         220 non-null    float64
 10  CGPA                    220 non-null    float64
 11  Current Back            220 non-null    float64
 12  Ever Back               220 non-null    int64
 13  GPA 2                   220 non-null    float64
 14  GPA 3                   220 non-null    float64
 15  GPA 4                   220 non-null    float64
 16  GPA 5                   220 non-null    float64
 17  GPA 6                   220 non-null    float64
 18  Olympiads Qualified     220 non-null    float64
 19  Technical Projects      220 non-null    float64
 20  Tech Quiz               220 non-null    float64
 21  Engg. Coaching          220 non-null    float64
 22  NTSE Scholarships       220 non-null    float64
 23  Miscellany Tech Events  220 non-null    float64
 24  Marks[10th]_normalized  220 non-null    float64
 25  Marks[12th]_normalized  220 non-null    float64
 26  GPA 1_normalized        220 non-null    float64
 27  CGPA_normalized         220 non-null    float64
dtypes: float64(22), int64(1), object(5)
memory usage: 49.8+ KB

None

### Variable Descriptions
Based on the dataset, here is a description of the key variables:

| Variable | Description | Type |
| :--- | :--- | :--- |
| **Branch** | Engineering department (CSE, ECE, CIVIL, etc.) | Categorical |
| **Marks [10th/12th]** | Percentage obtained in secondary/higher secondary | Numeric |
| **GPA 1-6** | Grade Point Average for semesters 1 through 6 | Numeric |
| **CGPA** | Cumulative Grade Point Average | Numeric |
| **Rank** | Entrance or internal merit rank | Numeric |
| **Ever Back** | Number of backlogs a student has had | Integer |
| **Gender** | Student gender | Categorical |