Title of the Assignment: Data Wrangling, I
Perform the following operations using Python on any open source dataset (e.g., data.csv)
Import all the required Python Libraries.
1. Locate open source data from the web (e.g. https://www.kaggle.com).
2. Provide a clear description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into the pandas data frame.
4. Data Preprocessing: check for missing values in the data using pandas insult(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables
etc. Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking
the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the
data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/Titanic-Dataset.csv')
display(df.head(10))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [3]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 2. Data Description and Source
**Source:** [Titanic - Machine Learning from Disaster (Kaggle)](https://www.kaggle.com/c/titanic/data)

**Description:** The Titanic dataset contains information about passengers on the Titanic, including whether they survived, their age, gender, passenger class, and ticket fare. It is commonly used for binary classification tasks.

In [6]:
# 4. Check dimensions of the dataframe
print(f"Dimensions of the dataframe: {df.shape}")

# Provide variable descriptions
# PassengerId: Unique ID, Survived: Target (0/1), Pclass: Ticket class, Name: Name,
# Sex: Gender, Age: Age in years, SibSp: # of siblings/spouses aboard,
# Parch: # of parents/children aboard, Ticket: Ticket number, Fare: Fare price,
# Cabin: Cabin number, Embarked: Port of embarkation

Dimensions of the dataframe: (891, 12)

### 5. Data Formatting and Normalization
We will check the data types and perform any necessary type conversions. For example, ensuring 'Embarked' is treated correctly and handling potential missing values before conversion.

In [7]:
# Check data types
print("Current Data Types:")
print(df.dtypes)

# Convert 'Survived' and 'Pclass' to categorical if needed for analysis,
# but for the assignment we ensure numeric types are correct.
# Example: Convert Embarked to category type
df['Embarked'] = df['Embarked'].astype('category')

# Handling missing values for Age by filling with median to allow for further steps
df['Age'] = df['Age'].fillna(df['Age'].median())

# Drop Cabin due to high missing values
df.drop(columns=['Cabin'], inplace=True)

print("\nUpdated Data Types:")
print(df.dtypes)

Current Data Types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Updated Data Types:
PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex              object
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
dtype: object

### 6. Turn Categorical Variables into Quantitative Variables
We will use Label Encoding or One-Hot Encoding for 'Sex' and 'Embarked'.

In [8]:
# Using map for binary variable 'Sex'
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# Using get_dummies for 'Embarked'
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

print("Dataframe after converting categorical variables:")
display(df.head())

Dataframe after converting categorical variables:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,True

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked_Q   891 non-null    bool
 11  Embarked_S   891 non-null    bool
dtypes: bool(2), float64(2), int64(6), object(2)
memory usage: 71.5+ KB

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,0.352413,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,0.477990,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,0.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,1.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
# Data Normalization: Scaling numeric features to a range of [0, 1]
# This is useful for many machine learning algorithms.
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

print("Data after Min-Max Normalization on Age and Fare:")
display(df[['Age', 'Fare']].head())

Data after Min-Max Normalization on Age and Fare:

        Age      Fare
0  0.271174  0.014151
1  0.472229  0.139136
2  0.321438  0.015469
3  0.434531  0.103644
4  0.434531  0.015713

### Comparison: Normalization vs. Standardization
- **Normalization (Min-Max):** Rescales to [0, 1]. Best when features have different scales but finite bounds.
- **Standardization (StandardScaler):** Centers data around mean 0 with unit variance. Best when data follows a Gaussian distribution or has outliers.

In [12]:
from sklearn.preprocessing import StandardScaler

# Let's create a copy to demonstrate standardization without losing our normalized data
df_standardized = df.copy()
std_scaler = StandardScaler()

# Standardizing Age and Fare
df_standardized[['Age', 'Fare']] = std_scaler.fit_transform(df_standardized[['Age', 'Fare']])

print("Data after Standardization (Mean ≈ 0, Std ≈ 1):")
display(df_standardized[['Age', 'Fare']].describe().round(4))

Data after Standardization (Mean ≈ 0, Std ≈ 1):

            Age      Fare
count  891.0000  891.0000
mean     0.0000    0.0000
std      1.0006    1.0006
min     -2.2242   -0.6484
25%     -0.5657   -0.4891
50%     -0.1046   -0.3574
75%      0.4333   -0.0242
max      3.8916    9.6672

### When to use which?

| Feature | Standardization (StandardScaler) | Normalization (Min-Max) |
| :--- | :--- | :--- |
| **Best For** | Algorithms that assume Gaussian (Normal) distribution (Linear Regression, Logistic Regression, LDA). | Algorithms that don't make distribution assumptions (KNN, Neural Networks). |
| **Outliers** | **Robust.** Outliers have less impact on the final range of most data points. | **Sensitive.** A single outlier can 'squash' all other values into a tiny range. |
| **Range** | Not bounded (usually -3 to 3, but can be anything). | Strictly bounded [0, 1] or [-1, 1]. |
| **Use Case Example** | Image processing or when you have extreme 'Fare' values that shouldn't break the model. | Algorithms where 'distance' or 'gradient' size matters strictly, like K-Nearest Neighbors or K-Means clustering. |